services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hono-app
    env_file:
      - devcontainer.env
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - postgres

  postgres:
    image: postgres:17.4
    container_name: hono-postgres
    env_file:
      - devcontainer.env
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres_network
    restart: always

volumes:
  postgres-data:

networks:
  postgres_network:
    driver: bridge
